

package org.tigris.scarab.om;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.manager.AbstractBaseManager;
import org.apache.torque.manager.CacheListener;
import org.apache.torque.manager.MethodResultCache;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;

/**
 * This class manages AttributeOption objects.
 * This class was autogenerated by Torque  *
 * You should not use this class directly.  It should not even be
 * extended all references should be to AttributeOptionManager
 */
public abstract class BaseAttributeOptionManager
    extends AbstractBaseManager
{
    /** The name of the manager */
    protected static String MANAGED_CLASS = "org.tigris.scarab.om.AttributeOption";

    /** The name of our class to pass to Torque as the default manager. */
    protected static String DEFAULT_MANAGER_CLASS
        = "org.tigris.scarab.om.AttributeOptionManager";

    /**
     * Retrieves an implementation of the manager, based on the settings in
     * the configuration.
     *
     * @return an implementation of AttributeOptionManager.
     */
    public static AttributeOptionManager getManager()
    {
        return (AttributeOptionManager)
            Torque.getManager(AttributeOptionManager.MANAGED_CLASS,
                AttributeOptionManager.DEFAULT_MANAGER_CLASS);
    }

    /**
     * Static accessor for the @see #getInstanceImpl().
     *
     * @return a <code>AttributeOption</code> value
     * @exception TorqueException if an error occurs
     */
    public static AttributeOption getInstance()
        throws TorqueException
    {
        return getManager().getInstanceImpl();
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @return a <code>AttributeOption</code> value
     * @exception TorqueException if an error occurs
     */
    public static AttributeOption getInstance(ObjectKey id)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id);
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey, boolean).
     *
     * @param id an <code>ObjectKey</code> value
     * @param fromCache if true, look for cached AttributeOptions before loading
     * from storage.
     * @return a <code>AttributeOption</code> value
     * @exception TorqueException if an error occurs
     */
    public static AttributeOption getInstance(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id, fromCache);
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @return a <code>AttributeOption</code> value
     * @exception TorqueException if an error occurs
     */
    public static AttributeOption getInstance(Integer id)
        throws TorqueException
    {
        return getManager().getInstanceImpl(SimpleKey.keyFor(id));
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @param fromCache if true, look for cached AttributeOptions before loading
     * from storage.
     * @return a <code>AttributeOption</code> value
     * @exception TorqueException if an error occurs
     */
    public static AttributeOption getInstance(Integer id, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstanceImpl(SimpleKey.keyFor(id), fromCache);
    }

    /**
     * Static accessor for the @see #getInstancesImpl(List).
     *
     * @param ids a <code>List</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids);
    }

    /**
     * Static accessor for the @see #getInstancesImpl(List, boolean).
     *
     * @param ids a <code>List</code> value
     * @param fromCache if true, look for cached AttributeOptions before loading
     * from storage.
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids, fromCache);
    }

    public static void putInstance(Persistent om)
        throws TorqueException
    {
        getManager().putInstanceImpl(om);
    }

    public static void clear()
        throws TorqueException
    {
        getManager().clearImpl();
    }

    public static boolean exists(AttributeOption obj)
        throws TorqueException
    {
        return getManager().existsImpl(obj);
    }

    public static MethodResultCache getMethodResult()
    {
        return getManager().getMethodResultCache();
    }

    public static void addCacheListener(CacheListener listener)
    {
        getManager().addCacheListenerImpl(listener);
    }

    /**
     * Creates a new <code>BaseAttributeOptionManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BaseAttributeOptionManager()
        throws TorqueException
    {
        setClassName("org.tigris.scarab.om.AttributeOption");
    }

    /**
     * Get a fresh instance of a AttributeOptionManager
     */
    protected AttributeOption getInstanceImpl()
        throws TorqueException
    {
        AttributeOption obj = null;
        try
        {
            obj = (AttributeOption) getOMInstance();
        }
        catch (Exception e)
        {
            throw new TorqueException(e);
        }
        return obj;
    }


    /**
     * Get a AttributeOption with the given id.
     *
     * @param id <code>ObjectKey</code> value
     */
    protected AttributeOption getInstanceImpl(ObjectKey id)
        throws TorqueException
    {
        return (AttributeOption) getOMInstance(id);
    }

    /**
     * Get a AttributeOption with the given id.
     *
     * @param id <code>ObjectKey</code> value
     * @param fromCache if true, look for cached AttributeOptions before loading
     * from storage.
     */
    protected AttributeOption getInstanceImpl(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return (AttributeOption) getOMInstance(id, fromCache);
    }

    /**
     * Gets a list of AttributeOptions based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @return a <code>List</code> of AttributeOptions
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids)
        throws TorqueException
    {
        return getOMs(ids);
    }

    /**
     * Gets a list of AttributeOptions based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @param fromCache if true, look for cached AttributeOptions before loading
     * from storage.
     * @return a <code>List</code> of AttributeOptions
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids, boolean fromCache)
        throws TorqueException
    {
        return getOMs(ids, fromCache);
    }

    /**
     * check for a duplicate project name
     */
    protected boolean existsImpl(AttributeOption om)
        throws TorqueException
    {
        Criteria crit = AttributeOptionPeer
            .buildCriteria((AttributeOption)om);
        return AttributeOptionPeer.doSelect(crit).size() > 0;
    }


    protected Persistent retrieveStoredOM(ObjectKey id)
        throws TorqueException
    {
        return AttributeOptionPeer.retrieveByPK(id);
    }

    /**
     * Gets a list of ModuleEntities based on id's.
     *
     * @param ids a <code>NumberKey[]</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    protected List retrieveStoredOMs(List ids)
        throws TorqueException
    {
        return AttributeOptionPeer.retrieveByPKs(ids);
    }
}
