

package org.tigris.scarab.om;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.manager.AbstractBaseManager;
import org.apache.torque.manager.CacheListener;
import org.apache.torque.manager.MethodResultCache;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;

/**
 * This class manages GlobalParameter objects.
 * This class was autogenerated by Torque  *
 * You should not use this class directly.  It should not even be
 * extended all references should be to GlobalParameterManager
 */
public abstract class BaseGlobalParameterManager
    extends AbstractBaseManager
{
    /** The name of the manager */
    protected static String MANAGED_CLASS = "org.tigris.scarab.om.GlobalParameter";

    /** The name of our class to pass to Torque as the default manager. */
    protected static String DEFAULT_MANAGER_CLASS
        = "org.tigris.scarab.om.GlobalParameterManager";

    /**
     * Retrieves an implementation of the manager, based on the settings in
     * the configuration.
     *
     * @return an implementation of GlobalParameterManager.
     */
    public static GlobalParameterManager getManager()
    {
        return (GlobalParameterManager)
            Torque.getManager(GlobalParameterManager.MANAGED_CLASS,
                GlobalParameterManager.DEFAULT_MANAGER_CLASS);
    }

    /**
     * Static accessor for the @see #getInstanceImpl().
     *
     * @return a <code>GlobalParameter</code> value
     * @exception TorqueException if an error occurs
     */
    public static GlobalParameter getInstance()
        throws TorqueException
    {
        return getManager().getInstanceImpl();
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @return a <code>GlobalParameter</code> value
     * @exception TorqueException if an error occurs
     */
    public static GlobalParameter getInstance(ObjectKey id)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id);
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey, boolean).
     *
     * @param id an <code>ObjectKey</code> value
     * @param fromCache if true, look for cached GlobalParameters before loading
     * from storage.
     * @return a <code>GlobalParameter</code> value
     * @exception TorqueException if an error occurs
     */
    public static GlobalParameter getInstance(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id, fromCache);
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @return a <code>GlobalParameter</code> value
     * @exception TorqueException if an error occurs
     */
    public static GlobalParameter getInstance(Integer id)
        throws TorqueException
    {
        return getManager().getInstanceImpl(SimpleKey.keyFor(id));
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @param fromCache if true, look for cached GlobalParameters before loading
     * from storage.
     * @return a <code>GlobalParameter</code> value
     * @exception TorqueException if an error occurs
     */
    public static GlobalParameter getInstance(Integer id, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstanceImpl(SimpleKey.keyFor(id), fromCache);
    }

    /**
     * Static accessor for the @see #getInstancesImpl(List).
     *
     * @param ids a <code>List</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids);
    }

    /**
     * Static accessor for the @see #getInstancesImpl(List, boolean).
     *
     * @param ids a <code>List</code> value
     * @param fromCache if true, look for cached GlobalParameters before loading
     * from storage.
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids, fromCache);
    }

    public static void putInstance(Persistent om)
        throws TorqueException
    {
        getManager().putInstanceImpl(om);
    }

    public static void clear()
        throws TorqueException
    {
        getManager().clearImpl();
    }

    public static boolean exists(GlobalParameter obj)
        throws TorqueException
    {
        return getManager().existsImpl(obj);
    }

    public static MethodResultCache getMethodResult()
    {
        return getManager().getMethodResultCache();
    }

    public static void addCacheListener(CacheListener listener)
    {
        getManager().addCacheListenerImpl(listener);
    }

    /**
     * Creates a new <code>BaseGlobalParameterManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BaseGlobalParameterManager()
        throws TorqueException
    {
        setClassName("org.tigris.scarab.om.GlobalParameter");
    }

    /**
     * Get a fresh instance of a GlobalParameterManager
     */
    protected GlobalParameter getInstanceImpl()
        throws TorqueException
    {
        GlobalParameter obj = null;
        try
        {
            obj = (GlobalParameter) getOMInstance();
        }
        catch (Exception e)
        {
            throw new TorqueException(e);
        }
        return obj;
    }


    /**
     * Get a GlobalParameter with the given id.
     *
     * @param id <code>ObjectKey</code> value
     */
    protected GlobalParameter getInstanceImpl(ObjectKey id)
        throws TorqueException
    {
        return (GlobalParameter) getOMInstance(id);
    }

    /**
     * Get a GlobalParameter with the given id.
     *
     * @param id <code>ObjectKey</code> value
     * @param fromCache if true, look for cached GlobalParameters before loading
     * from storage.
     */
    protected GlobalParameter getInstanceImpl(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return (GlobalParameter) getOMInstance(id, fromCache);
    }

    /**
     * Gets a list of GlobalParameters based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @return a <code>List</code> of GlobalParameters
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids)
        throws TorqueException
    {
        return getOMs(ids);
    }

    /**
     * Gets a list of GlobalParameters based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @param fromCache if true, look for cached GlobalParameters before loading
     * from storage.
     * @return a <code>List</code> of GlobalParameters
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids, boolean fromCache)
        throws TorqueException
    {
        return getOMs(ids, fromCache);
    }

    /**
     * check for a duplicate project name
     */
    protected boolean existsImpl(GlobalParameter om)
        throws TorqueException
    {
        Criteria crit = GlobalParameterPeer
            .buildCriteria((GlobalParameter)om);
        return GlobalParameterPeer.doSelect(crit).size() > 0;
    }


    protected Persistent retrieveStoredOM(ObjectKey id)
        throws TorqueException
    {
        return GlobalParameterPeer.retrieveByPK(id);
    }

    /**
     * Gets a list of ModuleEntities based on id's.
     *
     * @param ids a <code>NumberKey[]</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    protected List retrieveStoredOMs(List ids)
        throws TorqueException
    {
        return GlobalParameterPeer.retrieveByPKs(ids);
    }
}
