

package org.tigris.scarab.om;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.manager.AbstractBaseManager;
import org.apache.torque.manager.CacheListener;
import org.apache.torque.manager.MethodResultCache;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;

/**
 * This class manages RModuleUserAttribute objects.
 * This class was autogenerated by Torque  *
 * You should not use this class directly.  It should not even be
 * extended all references should be to RModuleUserAttributeManager
 */
public abstract class BaseRModuleUserAttributeManager
    extends AbstractBaseManager
{
    /** The name of the manager */
    protected static String MANAGED_CLASS = "org.tigris.scarab.om.RModuleUserAttribute";

    /** The name of our class to pass to Torque as the default manager. */
    protected static String DEFAULT_MANAGER_CLASS
        = "org.tigris.scarab.om.RModuleUserAttributeManager";

    /**
     * Retrieves an implementation of the manager, based on the settings in
     * the configuration.
     *
     * @return an implementation of RModuleUserAttributeManager.
     */
    public static RModuleUserAttributeManager getManager()
    {
        return (RModuleUserAttributeManager)
            Torque.getManager(RModuleUserAttributeManager.MANAGED_CLASS,
                RModuleUserAttributeManager.DEFAULT_MANAGER_CLASS);
    }

    /**
     * Static accessor for the @see #getInstanceImpl().
     *
     * @return a <code>RModuleUserAttribute</code> value
     * @exception TorqueException if an error occurs
     */
    public static RModuleUserAttribute getInstance()
        throws TorqueException
    {
        return getManager().getInstanceImpl();
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @return a <code>RModuleUserAttribute</code> value
     * @exception TorqueException if an error occurs
     */
    public static RModuleUserAttribute getInstance(ObjectKey id)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id);
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey, boolean).
     *
     * @param id an <code>ObjectKey</code> value
     * @param fromCache if true, look for cached RModuleUserAttributes before loading
     * from storage.
     * @return a <code>RModuleUserAttribute</code> value
     * @exception TorqueException if an error occurs
     */
    public static RModuleUserAttribute getInstance(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id, fromCache);
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @return a <code>RModuleUserAttribute</code> value
     * @exception TorqueException if an error occurs
     */
    public static RModuleUserAttribute getInstance(Long id)
        throws TorqueException
    {
        return getManager().getInstanceImpl(SimpleKey.keyFor(id));
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @param fromCache if true, look for cached RModuleUserAttributes before loading
     * from storage.
     * @return a <code>RModuleUserAttribute</code> value
     * @exception TorqueException if an error occurs
     */
    public static RModuleUserAttribute getInstance(Long id, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstanceImpl(SimpleKey.keyFor(id), fromCache);
    }

    /**
     * Static accessor for the @see #getInstancesImpl(List).
     *
     * @param ids a <code>List</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids);
    }

    /**
     * Static accessor for the @see #getInstancesImpl(List, boolean).
     *
     * @param ids a <code>List</code> value
     * @param fromCache if true, look for cached RModuleUserAttributes before loading
     * from storage.
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids, fromCache);
    }

    public static void putInstance(Persistent om)
        throws TorqueException
    {
        getManager().putInstanceImpl(om);
    }

    public static void clear()
        throws TorqueException
    {
        getManager().clearImpl();
    }

    public static boolean exists(RModuleUserAttribute obj)
        throws TorqueException
    {
        return getManager().existsImpl(obj);
    }

    public static MethodResultCache getMethodResult()
    {
        return getManager().getMethodResultCache();
    }

    public static void addCacheListener(CacheListener listener)
    {
        getManager().addCacheListenerImpl(listener);
    }

    /**
     * Creates a new <code>BaseRModuleUserAttributeManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BaseRModuleUserAttributeManager()
        throws TorqueException
    {
        setClassName("org.tigris.scarab.om.RModuleUserAttribute");
    }

    /**
     * Get a fresh instance of a RModuleUserAttributeManager
     */
    protected RModuleUserAttribute getInstanceImpl()
        throws TorqueException
    {
        RModuleUserAttribute obj = null;
        try
        {
            obj = (RModuleUserAttribute) getOMInstance();
        }
        catch (Exception e)
        {
            throw new TorqueException(e);
        }
        return obj;
    }


    /**
     * Get a RModuleUserAttribute with the given id.
     *
     * @param id <code>ObjectKey</code> value
     */
    protected RModuleUserAttribute getInstanceImpl(ObjectKey id)
        throws TorqueException
    {
        return (RModuleUserAttribute) getOMInstance(id);
    }

    /**
     * Get a RModuleUserAttribute with the given id.
     *
     * @param id <code>ObjectKey</code> value
     * @param fromCache if true, look for cached RModuleUserAttributes before loading
     * from storage.
     */
    protected RModuleUserAttribute getInstanceImpl(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return (RModuleUserAttribute) getOMInstance(id, fromCache);
    }

    /**
     * Gets a list of RModuleUserAttributes based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @return a <code>List</code> of RModuleUserAttributes
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids)
        throws TorqueException
    {
        return getOMs(ids);
    }

    /**
     * Gets a list of RModuleUserAttributes based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @param fromCache if true, look for cached RModuleUserAttributes before loading
     * from storage.
     * @return a <code>List</code> of RModuleUserAttributes
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids, boolean fromCache)
        throws TorqueException
    {
        return getOMs(ids, fromCache);
    }

    /**
     * check for a duplicate project name
     */
    protected boolean existsImpl(RModuleUserAttribute om)
        throws TorqueException
    {
        Criteria crit = RModuleUserAttributePeer
            .buildCriteria((RModuleUserAttribute)om);
        return RModuleUserAttributePeer.doSelect(crit).size() > 0;
    }


    protected Persistent retrieveStoredOM(ObjectKey id)
        throws TorqueException
    {
        return RModuleUserAttributePeer.retrieveByPK(id);
    }

    /**
     * Gets a list of ModuleEntities based on id's.
     *
     * @param ids a <code>NumberKey[]</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    protected List retrieveStoredOMs(List ids)
        throws TorqueException
    {
        return RModuleUserAttributePeer.retrieveByPKs(ids);
    }
}
