

package org.tigris.scarab.om;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.manager.AbstractBaseManager;
import org.apache.torque.manager.CacheListener;
import org.apache.torque.manager.MethodResultCache;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;

/**
 * This class manages RQueryUser objects.
 * This class was autogenerated by Torque  *
 * You should not use this class directly.  It should not even be
 * extended all references should be to RQueryUserManager
 */
public abstract class BaseRQueryUserManager
    extends AbstractBaseManager
{
    /** The name of the manager */
    protected static String MANAGED_CLASS = "org.tigris.scarab.om.RQueryUser";

    /** The name of our class to pass to Torque as the default manager. */
    protected static String DEFAULT_MANAGER_CLASS
        = "org.tigris.scarab.om.RQueryUserManager";

    /**
     * Retrieves an implementation of the manager, based on the settings in
     * the configuration.
     *
     * @return an implementation of RQueryUserManager.
     */
    public static RQueryUserManager getManager()
    {
        return (RQueryUserManager)
            Torque.getManager(RQueryUserManager.MANAGED_CLASS,
                RQueryUserManager.DEFAULT_MANAGER_CLASS);
    }

    /**
     * Static accessor for the @see #getInstanceImpl().
     *
     * @return a <code>RQueryUser</code> value
     * @exception TorqueException if an error occurs
     */
    public static RQueryUser getInstance()
        throws TorqueException
    {
        return getManager().getInstanceImpl();
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey).
     *
     * @param id an <code>ObjectKey</code> value
     * @return a <code>RQueryUser</code> value
     * @exception TorqueException if an error occurs
     */
    public static RQueryUser getInstance(ObjectKey id)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id);
    }

    /**
     * Static accessor for the @see #getInstanceImpl(ObjectKey, boolean).
     *
     * @param id an <code>ObjectKey</code> value
     * @param fromCache if true, look for cached RQueryUsers before loading
     * from storage.
     * @return a <code>RQueryUser</code> value
     * @exception TorqueException if an error occurs
     */
    public static RQueryUser getInstance(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstanceImpl(id, fromCache);
    }


    /**
     * Static accessor for the @see #getInstancesImpl(List).
     *
     * @param ids a <code>List</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids);
    }

    /**
     * Static accessor for the @see #getInstancesImpl(List, boolean).
     *
     * @param ids a <code>List</code> value
     * @param fromCache if true, look for cached RQueryUsers before loading
     * from storage.
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    public static List getInstances(List ids, boolean fromCache)
        throws TorqueException
    {
        return getManager().getInstancesImpl(ids, fromCache);
    }

    public static void putInstance(Persistent om)
        throws TorqueException
    {
        getManager().putInstanceImpl(om);
    }

    public static void clear()
        throws TorqueException
    {
        getManager().clearImpl();
    }

    public static boolean exists(RQueryUser obj)
        throws TorqueException
    {
        return getManager().existsImpl(obj);
    }

    public static MethodResultCache getMethodResult()
    {
        return getManager().getMethodResultCache();
    }

    public static void addCacheListener(CacheListener listener)
    {
        getManager().addCacheListenerImpl(listener);
    }

    /**
     * Creates a new <code>BaseRQueryUserManager</code> instance.
     *
     * @exception TorqueException if an error occurs
     */
    public BaseRQueryUserManager()
        throws TorqueException
    {
        setClassName("org.tigris.scarab.om.RQueryUser");
    }

    /**
     * Get a fresh instance of a RQueryUserManager
     */
    protected RQueryUser getInstanceImpl()
        throws TorqueException
    {
        RQueryUser obj = null;
        try
        {
            obj = (RQueryUser) getOMInstance();
        }
        catch (Exception e)
        {
            throw new TorqueException(e);
        }
        return obj;
    }


    /**
     * Get a RQueryUser with the given id.
     *
     * @param id <code>ObjectKey</code> value
     */
    protected RQueryUser getInstanceImpl(ObjectKey id)
        throws TorqueException
    {
        return (RQueryUser) getOMInstance(id);
    }

    /**
     * Get a RQueryUser with the given id.
     *
     * @param id <code>ObjectKey</code> value
     * @param fromCache if true, look for cached RQueryUsers before loading
     * from storage.
     */
    protected RQueryUser getInstanceImpl(ObjectKey id, boolean fromCache)
        throws TorqueException
    {
        return (RQueryUser) getOMInstance(id, fromCache);
    }

    /**
     * Gets a list of RQueryUsers based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @return a <code>List</code> of RQueryUsers
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids)
        throws TorqueException
    {
        return getOMs(ids);
    }

    /**
     * Gets a list of RQueryUsers based on id's.
     *
     * @param ids a List of <code>ObjectKeys</code> value
     * @param fromCache if true, look for cached RQueryUsers before loading
     * from storage.
     * @return a <code>List</code> of RQueryUsers
     * @exception TorqueException if an error occurs
     */
    protected List getInstancesImpl(List ids, boolean fromCache)
        throws TorqueException
    {
        return getOMs(ids, fromCache);
    }

    /**
     * check for a duplicate project name
     */
    protected boolean existsImpl(RQueryUser om)
        throws TorqueException
    {
        Criteria crit = RQueryUserPeer
            .buildCriteria((RQueryUser)om);
        return RQueryUserPeer.doSelect(crit).size() > 0;
    }


    protected Persistent retrieveStoredOM(ObjectKey id)
        throws TorqueException
    {
        return RQueryUserPeer.retrieveByPK(id);
    }

    /**
     * Gets a list of ModuleEntities based on id's.
     *
     * @param ids a <code>NumberKey[]</code> value
     * @return a <code>List</code> value
     * @exception TorqueException if an error occurs
     */
    protected List retrieveStoredOMs(List ids)
        throws TorqueException
    {
        return RQueryUserPeer.retrieveByPKs(ids);
    }
}
